apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ broker_operator_name }}-prom-k8s
  namespace: {{ broker_namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
